services:
  dev:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    volumes:
      - type: bind
        source: ..
        target: /workspace
      - type: bind
        source: ../setting/.atcodertools.toml
        target: /root/.atcodertools.toml
      - type: volume
        source: dummy
        target: /workspace/.venv
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  dummy:
